version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "shareit"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
